mapfusion:
    scancontext:
        knn_feature_dim: 64  # 分割的环数
        max_range: 32   #鸟瞰描述子的最大半径
        num_sector: 60   # 分割的扇区数
        num_nearest_matches: 2
        num_match_candidates: 1
        debug_col: 30
        debug_slide: 30
        debug_gap: 4
        UWB_topic: "/uwb/from/jackal0/A/to/jackal1/A"
        #vertial_axis: #should be x/y/z

    interRobot:
        #topic
        sc_topic: "context"
        sc_frame: "base_link"
        local_topic: "lio_sam/mapping/cloud_info"

        #thres
        loop_threshold: 0.8   # 描述子匹配阈值
        pcm_threshold: 20   # PCM马氏距离阈值越小越严格
        icp_threshold: 5    # icp匹配度评分越小越好
        loop_frame_threshold: 10 #frames
        pcm_start_threshold: 2   # 5 for best result, 2 for work in harsh environment

        robot_initial: "jackal0"
        use_position_search: false #use position search may introduce more global loop closure, but spend more time for candidate checking
